export default [
  {
    id:1,
    title:'ARCore Geospatial API Challenge',
    discription:'Lorem Ipsum is simply dummy text the printing and typesetting industry. Lorem Ipsum has been the standard dummy.',
    img:"./images/image1.png",
    location:'Online',
    eventType:"Hackthon",
    date: "December 05, 2021",
    timeLeft:13,
    page:"#",
    
  },
  {
    id:2,
    title:'ARCore Geospatial API Challenge',
    discription:'Lorem Ipsum is simply dummy text the printing and typesetting industry. Lorem Ipsum has been the standard dummy.',
    img:"./images/image2.png",
    location:'Online',
    eventType:"Hackthon",
    date: "December 05, 2021",
    timeLeft:13,
    page:"#",
  },
  {
    id:3,
    title:'ARCore Geospatial API Challenge',
    discription:'Lorem Ipsum is simply dummy text the printing and typesetting industry. Lorem Ipsum has been the standard dummy.',
    img:"./images/image3.png",
    location:'Online',
    eventType:"Hackthon",
    date: "December 05, 2021",
    timeLeft:13,
    page:"#",
  },
  {
    id:4,
    title:'ARCore Geospatial API Challenge',
    discription:'Lorem Ipsum is simply dummy text the printing and typesetting industry. Lorem Ipsum has been the standard dummy.',
    img:"./images/image4.png",
    location:'Online',
    eventType:"Hackthon",
    date: "December 05, 2021",
    timeLeft:13,
    page:"#",
  },
  {
    id:5,
    title:'ARCore Geospatial API Challenge',
    discription:'Lorem Ipsum is simply dummy text the printing and typesetting industry. Lorem Ipsum has been the standard dummy.',
    img:"./images/image5.png",
    location:'Online',
    eventType:"Hackthon",
    date: "December 05, 2021",
    timeLeft:13,
    page:"#",
  },
  {
    id:6,
    title:'ARCore Geospatial API Challenge',
    discription:'Lorem Ipsum is simply dummy text the printing and typesetting industry. Lorem Ipsum has been the standard dummy.',
    img:"./images/image6.png",
    location:'Online',
    eventType:"Hackthon",
    date: "December 05, 2021",
    timeLeft:13,
    page:"#",
  },
]